default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: lottery_development

test:
  <<: *default
  database: lottery_test

production:
  <<: *default
  database: lottery_production
  username: lottery_ajalvarez
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>